package com.lms.enums;

public enum ActionType {
    LOGIN,
    LOGOUT,
    CREATE_BOOK,
    UPDATE_BOOK,
    DELETE_BOOK,
    CREATE_ACCOUNT,
    UPDATE_ACCOUNT,
    DEACTIVATE_ACCOUNT,
    UPDATE_SETTINGS,
    REQUEST_BORROW,
    REQUEST_RETURN,
    RESERVE_BOOK,
    GOOGLE
}
