package com.lms.enums;

public enum ActionType {
    LOGIN,
    LOGOUT,
    CREATE_BOOK,
    UPDATE_BOOK,
    DELETE_BOOK,
    CREATE_ACCOUNT,
    UPDATE_ACCOUNT,
    DEACTIVATE_ACCOUNT,
    DELETE_ACCOUNT,
    UPDATE_SETTINGS,
    UPDATE_MEMBERSHIP_TIER,
    REQUEST_BORROW,
    REQUEST_RETURN,
    REQUEST_RENEWAL,
    CANCEL_RENEWAL,
    APPROVE_RENEWAL,
    REJECT_RENEWAL,
    RESERVE_BOOK,
    GOOGLE
}
