package com.lms.enums;

public enum NotificationEventType {
    GENERAL,
    MANUAL,
    LOAN_REQUESTED,
    LOAN_APPROVED,
    LOAN_REJECTED,
    LOAN_COLLECTED,
    LOAN_PICKUP_EXPIRED,
    RETURN_CONFIRMED,
    RENEWAL_APPROVED,
    RENEWAL_REJECTED,
    RESERVATION_APPROVED,
    RESERVATION_REJECTED,
    RESERVATION_DEPOSIT_PAID,
    RESERVATION_REFUNDED,
    OVERDUE_REMINDER,
    OVERDUE_FINE_CREATED,
    FINE_CREATED,
    FINE_PAID,
    TOP_UP_SUCCESS,
    REVIEW_REPLIED,
    REVIEW_APPROVED,
    REVIEW_REJECTED,
    ACQUISITION_APPROVED,
    ACQUISITION_REJECTED
}
